# Generated by Django 5.0.6 on 2024-05-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='users',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
